---
# Setup ClusterIssuer for LetsEncrypt, cloudflare-api-token secret must already be applied
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mike_demore@outlook.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: mike_demore@outlook.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token