apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: argocd-manifests
 namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/GitMoreDeMore/gitops.git'
    targetRevision: main
    path: argocd/argocd-manifests/
    directory:
      recurse: true
      exclude: applications/argocd-manifests.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true