apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GitMoreDeMore/gitops.git
    targetRevision: main
    path: argocd/argocd-manifests/projects
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd